### PR TITLE
only updating secured variables if the value has changed in terraform

### PR DESCRIPTION
**Pull request by thamdub**
**Current issue**
The bitbucket API returns an empty value for the repository and deployment variables if they are secured (this makes sense  as these values need to be protected).
The problem is that it prevents the provider from detecting a change and forces all the secured variables to be updated on every plan/apply.
This negatively impacts the readability of the plans and can lead to confusion (why is a resource that was not touched being updated?)

**Proposed solution**
Upon creation of a variable, a hash of the value will be generated and stored in the terraform state. On read, the provider will check if the current value and previous hash still match. If not, it will remove the value to force an update.
On successful update, the hash will also be updated.

### CODE REVIEW

**Comment by aeirola** [comment]
Sorry for the long delay, not really maintaining the provider as I'm not a go developer, but I'll try to take a look. So yeah, the secured variables are quite annoying then the API doesn't allow reading the value. Wondering what the best approach for these kind of asymmetric APIs is. Could maybe check what some of the larger providers like AWS or Azure do with data that can't be read from the API and try to mimic that.

**Comment by thamdub** [comment]
I don't think there are many options unfortunately. Since we can't read the "real" state, it's either:

- assume the value needs to be updated every time in case it was changed outside of terraform (current functionality). The drawback is that the plans get busy with unrelated changes, especially if you have a lot of variables.
- or assume the value is only managed through terraform and only needs to be updated if it changed in terraform (changes proposed in my PR). The drawback is that if the value is modified outside of terraform, there will be inconsistency between the actual state and the code.

A compromised might be to make the behavior configurable using an optional flag in the resource.

**Comment by aeirola** [comment]
The closest similar resource I could find in the official providers was the [`github_actions_secret`](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_secret), which uses some additional logic to identify remote changes based on timestamps (https://github.com/integrations/terraform-provider-github/blob/master/github/resource_github_actions_secret.go#L127). If we could get some information on when the secret was updated we could do something similar here.

If that fails, I think making the secret update behaviour configurable would be the best choice. A provider configuration would probably be more suitable compared to a resource based configuration.

**Comment by aeirola** [comment]
Tested the bitbucket API, and couldn't find any indication of wether the value has been changed or not. So yeah, the only way would then be to compare to the last value set by terraform.

P.S. I'll update the terraform SDK to the latest plugin SDK and release version 2.0.0 of the provider. This might cause some minor conflicts with this PR. Sorry for the inconvenience.

**Comment by dennislapchenko** [comment]
Bump! Hola. Can this get merged please? @aeirola

**Comment by aeirola** [comment]
Hi, @dennislapchenko! Yeah, sorry for letting the PR just hang for such a long time. There were open questions regarding how to handle the non-conventional behaviour of unknown values, and I didn't properly follow up on it. Sorry about that.

Unfortunately I need to inform you that this repository isn't maintained anymore. Since there are now many better maintained providers available, I'm going to deprecate this one completely and point users to the others. For now it seems as if https://github.com/DrFaust92/terraform-provider-bitbucket is the most active fork. You could try introducing this change into that provider instead. The author has stated that community contributions are welcome, and that he is committed to maintaining the provider.

Again, sorry for building up some false hope for the provider but not carrying the responsibility of properly keeping it up to date. Hopefully the other maintainers will do a better job of giving it the attention it really deserves.

**Comment by aeirola** [comment]
Closing this PR in favour of the other fork.

**Pull request closed without merging**
